name: Build and Package

permissions:
  contents: write
  packages: write

on:
  push:
    branches:
      - main
    tags:
      - 'v*.*.*'
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: Build Schemas (Java, Python, Tarball)
    runs-on: ubuntu-latest

    env:
      GRADLE_OPTS: "-Dorg.gradle.daemon=false"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Cache Gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle.kts', '**/settings.gradle.kts') }}
          restore-keys: |
            gradle-${{ runner.os }}-

      - name: Cache Python Wheels
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: pip-${{ runner.os }}-${{ hashFiles('**/pyproject.toml') }}
          restore-keys: |
            pip-${{ runner.os }}-

      - name: Install Python Build Tool
        run: pip install build

      - name: Run Gradle Build
        run: gradle build --stacktrace

      - name: List artifacts
        run: |
          echo "== Java Output =="
          find ./java/build/libs -type f -name "*.jar"
          echo "== Python Wheel Output =="
          find ./python/build/dist -type f -name "*.whl"
          echo "== Tarball Output =="
          find ./tar/build/distributions -type f -name "*.tar.gz"

      - name: Upload distribution artifacts
        uses: actions/upload-artifact@v4
        with:
          name: tile-schemas-artifacts
          path: |
            java/build/libs/*.jar
            tar/build/distributions/*.tar.gz
            python/build/dist/*.whl

  publish:
    if: startsWith(github.ref, 'refs/tags/v')
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download artifacts from build job
        uses: actions/download-artifact@v4
        with:
          name: tile-schemas-artifacts
          path: artifacts

      - name: Upload to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            artifacts/**/*.jar
            artifacts/**/*.whl
            artifacts/**/*.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}